version: '2'

services:
  postgres:
    image: postgres:12.8-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
#      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'mysql'
      MYSQL_PASSWORD: 'mysql'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
